HRWaveApp/urls.py
from django.urls import path
from . import views

app_name = 'HRWaveApp'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('employee_list/', views.employee_list, name='employee_list'),
    path('vacation_list/', views.vacation_list, name='vacation_list'),
    path('business_trip_list/', views.business_trip_list, name='business_trip_list'),
    path('sick_leave_list/', views.sick_leave_list, name='sick_leave_list'),
    path('employee_list/<int:employee_id>/', views.employee_detail, name='employee_detail'),
    path('create_employee/', views.create_employee, name='create_employee'),
    path('create_vacation/', views.create_vacation, name='create_vacation'),
    path('create_business_trip/', views.create_business_trip, name='create_business_trip'),
    path('create_sick_leave/', views.create_sick_leave, name='create_sick_leave'),
    path('edit_employee/<int:employee_id>/', views.edit_employee, name='edit_employee'),
    path('export_json/', views.export_json, name='export_json'),
    path('export_pdf/<int:employee_id>/', views.export_pdf, name='export_pdf'),
    path('vacation_pdf', views.vacation_pdf, name='vacation_pdf'),
    path('business_trip_pdf', views.business_trip_pdf, name='business_trip_pdf'),
    path('sick_leave_pdf', views.sick_leave_pdf, name='sick_leave_pdf'),
]

HRWaveCore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HRWaveApp.urls')),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hr_records.urls')),
]

HRWaveApp/forms.py
from django import forms
from .models import Employee, Vacation, BusinessTrip, SickLeave


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance.pk is None:
            self.fields['first_name'].initial = ''
            self.fields['last_name'].initial = ''
            self.fields['middle_name'].initial = ''
            self.fields['place_of_birth'].initial = ''
            self.fields['passport_series'].initial = ''
            self.fields['passport_number'].initial = ''
            self.fields['passport_issued_by'].initial = ''
            self.fields['passport_departament_code'].initial = ''
            self.fields['registration_address'].initial = ''
            self.fields['current_address'].initial = ''
            self.fields['position'].initial = ''
            self.fields['email'].initial = ''
            self.fields['phone_number'].initial = ''

    def clean(self):
        cleaned_data = super().clean()
        last_name = cleaned_data.get('last_name')
        first_name = cleaned_data.get('first_name')
        middle_name = cleaned_data.get('middle_name')
        position = cleaned_data.get('position')

        if last_name is not None:
            cleaned_data['last_name'] = last_name.capitalize()

        if first_name is not None:
            cleaned_data['first_name'] = first_name.capitalize()

        if middle_name is not None:
            cleaned_data['middle_name'] = middle_name.capitalize()

        if position is not None:
            cleaned_data['position'] = position.capitalize()

        return cleaned_data


class VacationForm(forms.ModelForm):
    class Meta:
        model = Vacation
        fields = ['type_vacation', 'start_date_vacation', 'end_date_vacation']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Проверяем, редактируется ли существующий сотрудник
        if self.instance.pk is None:
            # Если создается новый сотрудник, устанавливаем значение полей по умолчанию
            self.fields['type_vacation'].initial = ''


class BusinessTripForm(forms.ModelForm):
    class Meta:
        model = BusinessTrip
        fields = ['destination', 'start_date_business_trip', 'end_date_business_trip']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Проверяем, редактируется ли существующий сотрудник
        if self.instance.pk is None:
            # Если создается новый сотрудник, устанавливаем значение полей по умолчанию
            self.fields['destination'].initial = ''


class SickLeaveForm(forms.ModelForm):
    class Meta:
        model = SickLeave
        fields = ['reason', 'start_date_sick_leave', 'end_date_sick_leave']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Проверяем, редактируется ли существующий сотрудник
        if self.instance.pk is None:
            # Если создается новый сотрудник, устанавливаем значение полей по умолчанию
            self.fields['reason'].initial = ''

HRWaveApp/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Employee, Vacation, BusinessTrip, SickLeave
from .forms import EmployeeForm, VacationForm, BusinessTripForm, SickLeaveForm
from django.core.paginator import Paginator
from django.db.models import Q

# JSON
from django.http import JsonResponse, Http404
from urllib.parse import quote

# PDF
from django.http import FileResponse
from reportlab.lib.pagesizes import letter, portrait
from reportlab.pdfgen import canvas
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from io import BytesIO
from django.http import HttpResponse  #


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('HRWaveApp:employee_list')
        else:
            messages.error(request, 'Доступ запрещен. Проверьте учетные данные.')
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'HRWaveApp/login.html', context)


@login_required(login_url='HRWaveApp:login')
def logout_view(request):
    logout(request)
    return redirect('HRWaveApp:login')


@login_required(login_url='HRWaveApp:login')
def search_and_paginate(request, model, search_field, date_field_start, date_field_end, items_per_page):
    search_query = request.GET.get('q')
    year = request.GET.get('year')
    month = request.GET.get('month')

    queryset = model.objects.all().order_by(search_field)

    if search_query:
        search_query = search_query.capitalize()
        filter_kwargs = {f'{search_field}__icontains': search_query}
        queryset = queryset.filter(**filter_kwargs)

    if year:
        filter_condition = Q(**{f'{date_field_start}__year': year}) | Q(**{f'{date_field_end}__year': year})
        queryset = queryset.filter(filter_condition)

    if month:
        filter_condition = (Q(**{f'{date_field_start}__month': month}) | Q(**{f'{date_field_end}__month': month}))
        queryset = queryset.filter(filter_condition)

    if model != Employee:
        queryset = queryset.order_by('-' + date_field_start)

    paginator = Paginator(queryset, items_per_page)
    page_number = request.GET.get('page')
    items = paginator.get_page(page_number)
    return items, search_query


@login_required(login_url='HRWaveApp:login')
def employee_list(request):
    employees, search_query = search_and_paginate(request, Employee, 'last_name', None, None, 10)
    context = {'employees': employees, 'search_query': search_query, 'items': employees}
    return render(request, 'HRWaveApp/employee_list.html', context)


@login_required(login_url='HRWaveApp:login')
def vacation_list(request):
    vacations, search_query = search_and_paginate(request, Vacation, 'employee_vacation__last_name',
                                                  'start_date_vacation', 'end_date_vacation', 3)
    context = {'vacations': vacations, 'search_query': search_query, 'items': vacations}
    return render(request, 'HRWaveApp/vacation_list.html', context)


@login_required(login_url='HRWaveApp:login')
def business_trip_list(request):
    business_trips, search_query = search_and_paginate(request, BusinessTrip, 'employee_business_trip__last_name',
                                                       'start_date_business_trip', 'end_date_business_trip', 3)
    context = {'business_trips': business_trips, 'search_query': search_query, 'items': business_trips}
    return render(request, 'HRWaveApp/business_trip_list.html', context)


@login_required(login_url='HRWaveApp:login')
def sick_leave_list(request):
    sick_leaves, search_query = search_and_paginate(request, SickLeave, 'employee_sick_leave__last_name',
                                                    'start_date_sick_leave', 'end_date_sick_leave', 3)
    context = {'sick_leaves': sick_leaves, 'search_query': search_query, 'items': sick_leaves}
    return render(request, 'HRWaveApp/sick_leave_list.html', context)


@login_required(login_url='HRWaveApp:login')
def employee_detail(request, employee_id):
    employee = get_object_or_404(Employee, employee_id=employee_id)

    vacations = Vacation.objects.filter(employee_vacation=employee)
    vacations = vacations.order_by('-start_date_vacation')
    paginator = Paginator(vacations, 4)
    page_number = request.GET.get('vacations_page')
    vacations_page = paginator.get_page(page_number)

    business_trips = BusinessTrip.objects.filter(employee_business_trip=employee)
    business_trips = business_trips.order_by('-start_date_business_trip')
    business_trips_paginator = Paginator(business_trips, 4)
    business_trips_page_number = request.GET.get('business_trips_page')
    business_trips_page = business_trips_paginator.get_page(business_trips_page_number)

    sick_leaves = SickLeave.objects.filter(employee_sick_leave=employee)
    sick_leaves = sick_leaves.order_by('-start_date_sick_leave')
    sick_leaves_paginator = Paginator(sick_leaves, 4)
    sick_leaves_page_number = request.GET.get('sick_leaves_page')
    sick_leaves_page = sick_leaves_paginator.get_page(sick_leaves_page_number)

    context = {
        'employee': employee,
        'vacations_page': vacations_page,
        'business_trips_page': business_trips_page,
        'sick_leaves_page': sick_leaves_page
    }

    return render(request, 'HRWaveApp/employee_detail.html', context)


@login_required(login_url='HRWaveApp:login')
def create_employee(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('HRWaveApp:employee_list')
    else:
        form = EmployeeForm()

    context = {'form': form}
    return render(request, 'HRWaveApp/create_employee.html', context)


@login_required(login_url='HRWaveApp:login')
def create_record(request, record_type):
    employee_id = request.GET.get('employee_id')
    employee = Employee.objects.get(pk=employee_id)
    form = None

    if request.method == 'POST':
        if record_type == 'vacation':
            form = VacationForm(request.POST)
        elif record_type == 'business_trip':
            form = BusinessTripForm(request.POST)
        elif record_type == 'sick_leave':
            form = SickLeaveForm(request.POST)

        if form.is_valid():
            record = form.save(commit=False)
            setattr(record, f'employee_{record_type}_id', employee_id)
            record.save()
            return redirect('HRWaveApp:employee_list')
    else:
        if record_type == 'vacation':
            form = VacationForm()
        elif record_type == 'business_trip':
            form = BusinessTripForm()
        elif record_type == 'sick_leave':
            form = SickLeaveForm()

    context = {'form': form, 'employee': employee}
    return render(request, f'HRWaveApp/create_{record_type}.html', context)


@login_required(login_url='HRWaveApp:login')
def create_vacation(request):
    return create_record(request, 'vacation')


@login_required(login_url='HRWaveApp:login')
def create_business_trip(request):
    return create_record(request, 'business_trip')


@login_required(login_url='HRWaveApp:login')
def create_sick_leave(request):
    return create_record(request, 'sick_leave')


@login_required(login_url='HRWaveApp:login')
def edit_employee(request, employee_id):
    employee = get_object_or_404(Employee, employee_id=employee_id)

    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('HRWaveApp:employee_detail', employee_id=employee.employee_id)
    else:
        form = EmployeeForm(instance=employee)

    context = {'form': form, 'employee': employee}
    return render(request, 'HRWaveApp/edit_employee.html', context)


@login_required(login_url='HRWaveApp:login')
def export_json(request):
    employee_id = request.GET.get('employee_id')

    try:
        employee = Employee.objects.get(employee_id=employee_id)
    except Employee.DoesNotExist:
        raise Http404('Сотрудник не найден')

    employee_data = {
        'employee_id': employee.employee_id,
        'last_name': employee.last_name,
        'first_name': employee.first_name,
        'middle_name': employee.middle_name,
        'date_of_birth': employee.date_of_birth.strftime('%d/%m/%Y'),
        'place_of_birth': employee.place_of_birth,
        'passport_series': employee.passport_series,
        'passport_number': employee.passport_number,
        'passport_issued_by': employee.passport_issued_by,
        'passport_issued_date': employee.passport_issued_date.strftime('%d/%m/%Y'),
        'passport_departament_code': employee.passport_departament_code,
        'registration_address': employee.registration_address,
        'current_address': employee.current_address,
        'position': employee.position,
        'hire_date': employee.hire_date.strftime('%d/%m/%Y'),
        'email': employee.email,
        'phone_number': employee.phone_number,
        # Поля сотрудника
        'vacations': [{'type_vacation': vacation.type_vacation,
                       'start_date': vacation.start_date_vacation.strftime('%d/%m/%Y'),
                       'end_date': vacation.end_date_vacation.strftime('%d/%m/%Y')}
                      for vacation in employee.vacation_set.all()],
        'business_trips': [{'destination': business_trip.destination,

HRWaveApp/templates/HRWaveApp/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HRWave</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <!-- Навигационная панель Bootstrap 4 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">HRWave</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'HRWaveApp:employee_list' %}">Сотрудники</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'HRWaveApp:vacation_list' %}">Отпуска</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'HRWaveApp:business_trip_list' %}">Командировки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'HRWaveApp:sick_leave_list' %}">Больничные</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'HRWaveApp:logout' %}">Выход</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid">
        {% block content %}{% endblock content %}
    </div>

</body>
</html>

HRWaveApp/templates/HRWaveApp/employee_detail.html
{% extends 'HRWaveApp/base.html' %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Сотрудник: {{ employee.last_name }} {{ employee.first_name }}
                </div>
                <div class="card-body">
                    <p>Идентификатор сотрудника: {{ employee.employee_id }}</p>
                    <p>Имя: {{ employee.first_name }}</p>
                    <p>Фамилия: {{ employee.last_name }}</p>
                    <p>Отчество: {{ employee.middle_name }}</p>
                    <p>Дата рождения: {{ employee.date_of_birth }}</p>
                    <p>Место рождения: {{ employee.place_of_birth }}</p>
                    <p>Серия паспорта: {{ employee.passport_series }}</p>
                    <p>Номер паспорта: {{ employee.passport_number }}</p>
                    <p>Паспорт выдан: {{ employee.passport_issued_by }}</p>
                    <p>Дата выдачи паспорта: {{ employee.passport_issued_date }}</p>
                    <p>Код подразделения: {{ employee.passport_departament_code }}</p>
                    <p>Адрес регистрации: {{ employee.registration_address }}</p>
                    <p>Адрес проживания: {{ employee.current_address }}</p>
                    <p>Должность: {{ employee.position }}</p>
                    <p>Дата приема на работу: {{ employee.hire_date }}</p>
                    <p>Почта: {{ employee.email }}</p>
                    <p>Номер телефона: {{ employee.phone_number }}</p>
                </div>
            </div>

			<div class="row justify-content-around mb-3">

			    <div class="col-sm-3 mt-3">
			        <div class="text-center">
			            <a class="btn btn-danger btn-block" href="{% url 'HRWaveApp:employee_list' %}">Вернуться</a>
			        </div>
			    </div>

			    <div class="col-sm-3 mt-3">
			        <div class="text-center">
			            <a class="btn btn-success btn-block" href="{% url 'HRWaveApp:edit_employee' employee_id=employee.employee_id %}">Редактировать</a>
			        </div>
			    </div>

			    <div class="col-sm-3 mt-3">
			        <div class="text-center">
			            <a class="btn btn-info btn-block" href="{% url 'HRWaveApp:export_json' %}?employee_id={{ employee.employee_id }}">Экспорт в JSON</a>
			        </div>
			    </div>

			    <div class="col-sm-3 mt-3">
			        <div class="text-center">
			            <a class="btn btn-info btn-block" href="{% url 'HRWaveApp:export_pdf' employee_id=employee.employee_id %}">Экспорт в PDF</a>
			        </div>
			    </div>

			</div>

        </div>


        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2>Отпуска</h2>
                </div>
                <div class="card-body">
                    <ul class="mb-0">
                        {% for vacation in vacations_page %}
                            <li>С {{ vacation.start_date_vacation }} по {{ vacation.end_date_vacation }}</li>
                        {% empty %}
                            <li>Нет данных об отпусках</li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Пагинация для отпусков -->
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if vacations_page.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?vacations_page=1" aria-label="Первая">
                                    <span aria-hidden="true">&laquo;&laquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?vacations_page={{ vacations_page.previous_page_number }}" aria-label="Предыдущая">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}
                        <li class="page-item disabled">
                            <span class="page-link">Страница {{ vacations_page.number }} из {{ vacations_page.paginator.num_pages }}</span>
                        </li>
                        {% if vacations_page.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?vacations_page={{ vacations_page.next_page_number }}" aria-label="Следующая">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?vacations_page={{ vacations_page.paginator.num_pages }}" aria-label="Последняя">
                                    <span aria-hidden="true">&raquo;&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>



            <div class="card mt-3">
                <div class="card-header">
                    <h2>Командировки</h2>
                </div>
                <div class="card-body">
                    <ul class="mb-0">
                        {% for business_trip in business_trips_page %}
                            <li>С {{ business_trip.start_date_business_trip }} по {{ business_trip.end_date_business_trip }}</li>
                        {% empty %}
                            <li>Нет данных о командировках</li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Пагинация для командировок -->
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if business_trips_page.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?business_trips_page=1" aria-label="Первая">
                                    <span aria-hidden="true">&laquo;&laquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?business_trips_page={{ business_trips_page.previous_page_number }}" aria-label="Предыдущая">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}
                        <li class="page-item disabled">
                            <span class="page-link">Страница {{ business_trips_page.number }} из {{ business_trips_page.paginator.num_pages }}</span>
                        </li>
                        {% if business_trips_page.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?business_trips_page={{ business_trips_page.next_page_number }}" aria-label="Следующая">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?business_trips_page={{ business_trips_page.paginator.num_pages }}" aria-label="Последняя">
                                    <span aria-hidden="true">&raquo;&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>


            <div class="card mt-3">
                <div class="card-header">
                    <h2>Больничные</h2>
                </div>
                <div class="card-body">
                    <ul class="mb-0">
                        {% for sick_leave in sick_leaves_page %}
                            <li>С {{ sick_leave.start_date_sick_leave }} по {{ sick_leave.end_date_sick_leave }}</li>
                        {% empty %}
                            <li>Нет данных о больничных</li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Пагинация для больничных -->
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if sick_leaves_page.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?sick_leaves_page=1" aria-label="Первая">
                                    <span aria-hidden="true">&laquo;&laquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?sick_leaves_page={{ sick_leaves_page.previous_page_number }}" aria-label="Предыдущая">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}
                        <li class="page-item disabled">
                            <span class="page-link">Страница {{ sick_leaves_page.number }} из {{ sick_leaves_page.paginator.num_pages }}</span>
                        </li>
                        {% if sick_leaves_page.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?sick_leaves_page={{ sick_leaves_page.next_page_number }}" aria-label="Следующая">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?sick_leaves_page={{ sick_leaves_page.paginator.num_pages }}" aria-label="Последняя">
                                    <span aria-hidden="true">&raquo;&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>

	</div>


</div>

{% endblock content %}

HRWaveApp/templates/HRWaveApp/employee_list.html
{% extends 'HRWaveApp/base.html' %}

{% block content %}

    <!-- Поиск -->
	<form method="GET" class="form-inline mt-3">
	    <div class="form-group mb-2 col-md-8">
	        <input type="text" name="q" class="form-control w-100" placeholder="Поиск по фамилии" value="{{ request.GET.q }}">
	    </div>
	    <div class="form-group mb-2 col-md-2">
	        <button type="submit" class="btn btn-primary btn-block">Искать</button>
	    </div>
	    <div class="form-group mb-2 col-md-2">
	        <a href="{% url 'HRWaveApp:create_employee' %}" class="btn btn-success btn-block">Добавить</a>
	    </div>
	</form>

    <ul class="list-group mt-2">
        {% for employee in employees %}
            <li class="list-group-item">
                <div class="row d-flex align-items-center">
                    <div class="col">
                        <a class="text-decoration-none" href="{% url 'HRWaveApp:employee_detail' employee.employee_id %}">
                            {{ employee.last_name }} {{ employee.first_name }}
                        </a>
                    </div>

				<div class="col text-right">
				    <div class="btn-group" role="group">
				        <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown"
				                aria-haspopup="true" aria-expanded="false">
				            Действия
				        </button>
				        <div class="dropdown-menu dropdown-menu-right">
				            <a class="dropdown-item" href="{% url 'HRWaveApp:create_vacation' %}?employee_id={{ employee.employee_id }}">Создать отпуск</a>
				            <a class="dropdown-item" href="{% url 'HRWaveApp:create_business_trip' %}?employee_id={{ employee.employee_id }}">Создать командировку</a>
				            <a class="dropdown-item" href="{% url 'HRWaveApp:create_sick_leave' %}?employee_id={{ employee.employee_id }}">Создать больничный</a>
					        <div class="dropdown-divider"></div>
					        <a class="dropdown-item" href="{% url 'HRWaveApp:export_json' %}?employee_id={{ employee.employee_id }}">Экспорт В JSON</a>
				            <a class="dropdown-item" href="{% url 'HRWaveApp:export_pdf' employee_id=employee.employee_id %}">Экспорт в PDF</a>
				            <div class="dropdown-divider"></div>
					        <a class="dropdown-item" href="{% url 'HRWaveApp:edit_employee' employee_id=employee.employee_id %}">Редактировать</a>
				        </div>
				    </div>
				</div>


                </div>
            </li>
        {% empty %}
            <li class="mx-5">Нет данных</li>
        {% endfor %}
    </ul>

	<!-- Пагинатор -->
	<nav aria-label="Page navigation" class="mt-3">
	    <ul class="pagination justify-content-center">
	        {% if items.has_previous %}
	            <li class="page-item">
	                <a class="page-link" href="?page=1{% if search_query %}&q={{ search_query }}{% endif %}" aria-label="Первая">
	                    <span aria-hidden="true">&laquo;&laquo;</span>
	                </a>
	            </li>
	            <li class="page-item">
	                <a class="page-link" href="?page={{ items.previous_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}" aria-label="Предыдущая">
	                    <span aria-hidden="true">&laquo;</span>
	                </a>
	            </li>
	        {% endif %}
	        <li class="page-item disabled">
	            <span class="page-link">Страница {{ items.number }} из {{ items.paginator.num_pages }}</span>
	        </li>
	        {% if items.has_next %}
	            <li class="page-item">
	                <a class="page-link" href="?page={{ items.next_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}" aria-label="Следующая">
	                    <span aria-hidden="true">&raquo;</span>
	                </a>
	            </li>
	            <li class="page-item">
	                <a class="page-link" href="?page={{ items.paginator.num_pages }}{% if search_query %}&q={{ search_query }}{% endif %}" aria-label="Последняя">
	                    <span aria-hidden="true">&raquo;&raquo;</span>
	                </a>
	            </li>
	        {% endif %}
	    </ul>
	</nav>

{% endblock content %}